version: '3'

services:

    ireceptor-mysql:
        image: mysql/mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: Qz7WHjtZzZjZsHUL3tAv7yh7nNBH38e994jRZDPeYbdzhnYBCeU4bdC9rqESDtje
            MYSQL_USER: ireceptor
            MYSQL_PASSWORD: KPzKLctFMgS9XxkEFpEXHbNeyVeSHNnhDcEq4Gq7696M5Umm2EBdGDn5eRpQXyQ3
            MYSQL_DATABASE: ireceptorgw

    ireceptor-mongodb:
        image: mongo:4
        environment:
            MONGO_INITDB_DATABASE: ireceptor

    ireceptor-gateway:
        depends_on:
            - ireceptor-mysql
            - ireceptor-mongodb
        build:
            context: ./gateway
        image: webapp:tag
        environment:
            DB_HOST: ireceptor-mysql
            DB_DATABASE: ireceptorgw
            DB_USERNAME: ireceptor
            DB_PASSWORD: KPzKLctFMgS9XxkEFpEXHbNeyVeSHNnhDcEq4Gq7696M5Umm2EBdGDn5eRpQXyQ3
            CACHE_DB_HOST: ireceptor-mongodb
            CACHE_DB_DATABASE: ireceptor
        ports:
            - ${GATEWAY_PORT:-80}:80
