version: '3'

services:

    ireceptor-mysql:
        image: mysql/mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: Qz7WHjtZzZjZsHUL3tAv7yh7nNBH38e994jRZDPeYbdzhnYBCeU4bdC9rqESDtje
            MYSQL_USER: ireceptor
            MYSQL_PASSWORD: KPzKLctFMgS9XxkEFpEXHbNeyVeSHNnhDcEq4Gq7696M5Umm2EBdGDn5eRpQXyQ3
            MYSQL_DATABASE: ireceptorgw

    ireceptor-mongodb:
        image: mongo:4
        environment:
            MONGO_INITDB_DATABASE: cache

    ireceptor-gateway:
        depends_on:
            - ireceptor-mysql
            - ireceptor-mongodb
        image: ireceptor/gateway:${GATEWAY_TAG:-docker}
        environment:
            DB_HOST: ireceptor-mysql
            DB_DATABASE: ireceptorgw
            DB_USERNAME: ireceptor
            DB_PASSWORD: KPzKLctFMgS9XxkEFpEXHbNeyVeSHNnhDcEq4Gq7696M5Umm2EBdGDn5eRpQXyQ3
            CACHE_DB_HOST: ireceptor-mongodb
            IRECEPTOR_SEEDERS_DATA_FOLDER: /data
        ports:
            - ${GATEWAY_PORT:-80}:80
        volumes:
            - ../data:/data
